# Generated by Django 4.2.5 on 2023-11-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_alter_myuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='BITS_ID',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
