# Generated by Django 4.2.5 on 2023-11-24 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0005_dish_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
