# Generated by Django 4.2.5 on 2023-12-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0009_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_json', models.JSONField(null=True, verbose_name='menu')),
            ],
        ),
    ]
