# Generated by Django 4.2.7 on 2023-12-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0011_menu_date_menudishentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_json',
        ),
    ]
